### ISSUE TITLE
godaddy hosting is not supporting wish.php's all codes

### ISSUE THREAD

**Issue by SantoshNayak** [mskian/happy-New-year-Wishing-web-app#2]
we have  324 line of code in wish.php but after uploading this to my cpanel and opening the code editor in cpanel only 247 lines of codes are showing. but working perfectly with xampp.
so there might some issues with php version.
please check it

**Comment by mskian** [comment]
did you copy and paste code fully?

**Comment by SantoshNayak** [comment]
Yes bhai

**Comment by mskian** [comment]
issue fixed?

**Comment by SantoshNayak** [comment]
No bhai
Need you help

**Comment by mskian** [comment]
sure 
your PHP version?
Server?

**Comment by SantoshNayak** [comment]
I have tried changing my php version still not working.
Using godaddy shared hosting
